export const CROWD_FAVORITE_TEST_OPT_IN_START = 1775527200000; // Apr 6, 2026 9:00 PM CDT
export const CROWD_FAVORITE_TEST_OPT_IN_END = 1775534400000; // Apr 6, 2026 11:00 PM CDT

export const CROWD_FAVORITE_MAX_TEAM_MEMBERS = 4;
export const CROWD_FAVORITE_MAX_ADDITIONAL_MEMBERS = CROWD_FAVORITE_MAX_TEAM_MEMBERS - 1;

export const isCrowdFavoriteOptInOpen = (now = Date.now()) => {
  return now >= CROWD_FAVORITE_TEST_OPT_IN_START && now <= CROWD_FAVORITE_TEST_OPT_IN_END;
};
